// symbol groups

DEFCHAR(la, 'a')
DEFCHAR(lb, 'b')
DEFCHAR(lc, 'c')
DEFCHAR(ld, 'd')
DEFCHAR(le, 'e')
DEFCHAR(lf, 'f')
DEFCHAR(lg, 'g')
DEFCHAR(lh, 'h')
DEFCHAR(li, 'i')
DEFCHAR(lj, 'j')
DEFCHAR(lk, 'k')
DEFCHAR(ll, 'l')
DEFCHAR(lm, 'm')
DEFCHAR(ln, 'n')
DEFCHAR(lo, 'o')
DEFCHAR(lp, 'p')
DEFCHAR(lq, 'q')
DEFCHAR(lr, 'r')
DEFCHAR(ls, 's')
DEFCHAR(lt, 't')
DEFCHAR(lu, 'u')
DEFCHAR(lv, 'v')
DEFCHAR(lw, 'w')
DEFCHAR(lx, 'x')
DEFCHAR(ly, 'y')
DEFCHAR(lz, 'z')
DEFGROUP(lletters,
		S(la) S(lb) S(lc) S(ld) S(le) S(lf) S(lg) S(lh) S(li) S(lj) S(lk) S(ll) S(lm) S(ln) S(lo) S(lp) S(lq) S(lr) S(ls) S(lt) S(lu) S(lv) S(lw) S(lx) S(ly) S(lz))

DEFCHAR(ca, 'A')
DEFCHAR(cb, 'B')
DEFCHAR(cc, 'C')
DEFCHAR(cd, 'D')
DEFCHAR(ce, 'E')
DEFCHAR(cf, 'F')
DEFCHAR(cg, 'G')
DEFCHAR(ch, 'H')
DEFCHAR(ci, 'I')
DEFCHAR(cj, 'J')
DEFCHAR(ck, 'K')
DEFCHAR(cl, 'L')
DEFCHAR(cm, 'M')
DEFCHAR(cn, 'N')
DEFCHAR(co, 'O')
DEFCHAR(cp, 'P')
DEFCHAR(cq, 'Q')
DEFCHAR(cr, 'R')
DEFCHAR(cs, 'S')
DEFCHAR(ct, 'T')
DEFCHAR(cu, 'U')
DEFCHAR(cv, 'V')
DEFCHAR(cw, 'W')
DEFCHAR(cx, 'X')
DEFCHAR(cy, 'Y')
DEFCHAR(cz, 'Z')
DEFGROUP(cletters,
		S(ca) S(cb) S(cc) S(cd) S(ce) S(cf) S(cg) S(ch) S(ci) S(cj) S(ck) S(cc) S(cm) S(cn) S(co) S(cp) S(cq) S(cr) S(cs) S(ct) S(cu) S(cv) S(cw) S(cx) S(cy) S(cz))

DEFGROUP(letters, S(lletters) S(cletters))

DEFCHAR(d0, '0')
DEFCHAR(d1, '1')
DEFCHAR(d2, '2')
DEFCHAR(d3, '3')
DEFCHAR(d4, '4')
DEFCHAR(d5, '5')
DEFCHAR(d6, '6')
DEFCHAR(d7, '7')
DEFCHAR(d8, '8')
DEFCHAR(d9, '9')
DEFGROUP(digits, S(d0) S(d1) S(d2) S(d3) S(d4) S(d5) S(d6) S(d7) S(d8) S(d9))

DEFCHAR(openpar, '(')
DEFCHAR(closepar, ')')
DEFCHAR(openbrace, '{')
DEFCHAR(closebrace, '}')
DEFCHAR(opensquare, '[')
DEFCHAR(closesquare, ']')
DEFCHAR(opentriangle, '<')
DEFCHAR(closetriangle, '>')
DEFCHAR(tilde, '~')
DEFCHAR(grave, '`')
DEFCHAR(exclamation, '!')
DEFCHAR(at, '@')
DEFCHAR(hash, '#')
DEFCHAR(dollar, '$')
DEFCHAR(percent, '%')
DEFCHAR(carrot, '^')
DEFCHAR(ampersand, '&')
DEFCHAR(asterisk, '*')
DEFCHAR(minus, '-')
DEFCHAR(underscore, '_')
DEFCHAR(plus, '+')
DEFCHAR(equals, '=')
DEFCHAR(pipe, '|')
DEFCHAR(backslash, '\\')
DEFCHAR(forewardslash, '/')
DEFCHAR(singlequote, '\'')
DEFCHAR(doublequote, '"')
DEFCHAR(colon, ':')
DEFCHAR(semicolon, ';')
DEFCHAR(comma, ',')
DEFCHAR(dot, '.')
DEFCHAR(question, '?')
DEFCHAR(space, ' ')
DEFCHAR(tab, '\t')
DEFCHAR(newline, '\n')

DEFGROUP(whitespace, S(space) S(tab) S(newline))
DEFGROUP(brackets,
		S(openpar) S(closepar) S(openbrace) S(closebrace) S(opensquare) S(closesquare) S(opentriangle) S(closetriangle))
DEFGROUP(special,
		S(brackets) S(tilde) S(grave) S(exclamation) S(at) S(hash) S(dollar) S(percent) S(carrot) S(carrot) S(ampersand) S(asterisk) S(minus) S(underscore) S(plus) S(equals) S(pipe) S(backslash) S(forewardslash) S(singlequote) S(doublequote) S(colon) S(semicolon) S(comma) S(dot) S(question) S(space) S(tab))

DEFMANY(requirewhitespace, S(whitespace))
DEFVARIABLE(optionalwhitespace, S(whitespace))

// string
DEFLITERAL(escapeddoublequote, S(backslash) S(doublequote))
DEFGROUP(stringcharacter,
		S(brackets) S(tilde) S(grave) S(exclamation) S(at) S(hash) S(dollar) S(percent) S(carrot) S(carrot) S(ampersand) S(asterisk) S(minus) S(underscore) S(plus) S(equals) S(pipe) S(backslash) S(forewardslash) S(escapeddoublequote) S(singlequote) S(colon) S(semicolon) S(comma) S(dot) S(question) S(space) S(tab))
DEFVARIABLE(stringcontents, S(stringcharacter))
DEFLITERAL(stringliteral, S(doublequote) S(stringcontents) S(doublequote))

// === numbers
DEFMANY(manydigits, S(digits))

// integer
DEFLITERAL(integerliteral, S(manydigits))

// decimal
DEFLITERAL(decimalliteral, S(manydigits) S(dot) S(manydigits))

// hex
DEFGROUP(hexcontents, S(digits) S(la)S(ca) S(lb)S(cb) S(lc)S(cc) S(ld)S(cd) S(le)S(ce) S(lf)S(cf))
DEFLITERAL(hexliteral, S(d0) S(lx) S(hexcontents))

DEFGROUP(symbolfirstcharoptions, S(letters) S(underscore) S(at))
DEFMANY(symbolfirstchar, S(symbolfirstcharoptions))
DEFGROUP(symbolrestcharoptions, S(letters) S(underscore) S(at) S(digits))
DEFVARIABLE(symbolrestchar, S(symbolrestcharoptions))
DEFLITERAL(symbol, S(symbolfirstchar) S(symbolrestchar))

// definition
DEFLITERAL(defkeyword, S(ld) S(le) S(lf))
DEFLITERAL(define, S(defkeyword) S(requirewhitespace) S(symbol) S(requirewhitespace) S(symbol))
